
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Status = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  PROCESSING: 'PROCESSING',
  CANCELED: 'CANCELED',
  SOLD: 'SOLD'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const OrderStatus = {
  OPEN: 'OPEN',
  PROCESSING: 'PROCESSING',
  CANCELED: 'CANCELED',
  FINISHED: 'FINISHED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const ModType = {
  DIABLO: 'DIABLO'
} as const

export type ModType = (typeof ModType)[keyof typeof ModType]
